Fix search for video_id extension
If we're unlucky the random video_id may contain the letters "jpg"
without containing the string ".jpg", causing this traceback:

  Traceback (most recent call last):
    File "./twitter-to-rss.py", line 41, in <module>
      for (n, tweet) in enumerate(twitter_scraper.get_tweets(user, pages=10)):
    File "/usr/local/lib/python3.7/site-packages/twitter_scraper/modules/tweets.py", line 134, in get_tweets
      yield from gen_tweets(pages)
    File "/usr/local/lib/python3.7/site-packages/twitter_scraper/modules/tweets.py", line 106, in gen_tweets
      video_id = tmp[:tmp.index('.jpg')] if 'jpg' in tmp \
  ValueError: substring not found